### ISSUE TITLE
Exception docker not catch

### ISSUE THREAD

**Issue by ylorenza** [voyages-sncf-technologies/maze#10]
Salut,

de temps en temps je me prend ce genre d'exception (surement la faute de centos)
Mais j'aimerais bien savoir d'ou ça vient quand même et éventuellement que les tests qui sont après tente de s’exécuter. ça serait pas mal de la catcher pour log un truc, meme si on se contente de la propager apres.

[31mcom.vsct.dt.components.redis.cluster.RedisClusterTest *** ABORTED ***[0m
[31m  com.github.dockerjava.api.exception.NotFoundException: linux runtime spec devices: lstat /dev/block/253:16: no such file or directory[0m
[31m  at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)[0m
[31m  at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)[0m
[31m  at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)[0m
[31m  at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)[0m
[31m  at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)[0m
[31m  at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)[0m
[31m  at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)[0m
[31m  at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[0m
[31m  at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[0m
[31m  at org.glassfish.jersey.internal.Errors.process(Errors.java:228)[0m
[31m  ...[0m

**Comment by larochef** [comment]
J'ai déjà eu ce genre d'erreur oui. Ce que je ne sais pas trop, c'est si c'est dû à docker ou à l'indus vsct des postes de travail ;)

**Comment by ylorenza** [comment]
C'est un peu les deux. Ce que je peu dire c'est que je ne la reproduit plus depuis que je suis passé en overlay2 sur mon poste. Mais en tans que dev maze c'est pas notre probleme si les install docker sont pas hyper clean.

Par contre, ça m'aiderai a debug de savoir quel action maze provoque cette exeception. Je vais voir pour rajouter un try catch et log l'exception

**Comment by larochef** [comment]
De mémoire je l'avais surtout lors de la création des conteneurs

**Comment by ylorenza** [comment]
A priori, onne pu ien y faire, donc je close
