### ISSUE TITLE
Reference a vsct dans Docker.prepareCreateContainer

### ISSUE THREAD

**Issue by ylorenza** [voyages-sncf-technologies/maze#12]
Salut ,

Dans le code on a .withDnsSearch("socrate.vsct.fr")
Faudrait rendre parametrable ce truc la et le sortir du core

**Comment by larochef** [comment]
Je suis d'accord avec toi. Une solution serait d'avoir un objet de configuration dans l'objet Docker qui puisse être changé par l'utilisateur pour jouter des personnalisations (dns, nom du réseau, plage d'ips du réseau, etc...)

**Comment by larochef** [comment]
Du coup, on pourrait peu être également utiliser cet objet de configuration pour ajouter des labels (cf. #7 )

**Comment by larochef** [comment]
Je commence à regarder ce que ça donnerait, sur la branche "review-configuration"

**Comment by larochef** [comment]
Corrigé par #13
