### ISSUE TITLE
L'ip interne d'un container peut changer au reboot de celui-ci

### ISSUE THREAD

**Issue by ylorenza** [voyages-sncf-technologies/maze#4]
Salut François,

J'ai constaté (et lu un peu partout) que docker peu changer l'ip interne d'un container apres un stop/start.
Il faut donc la mettre a jour lors d'un startStoppedNode afin d'etre sur d'avoir toujours la bonne ip.

J'ai une pr sur le feu qui corrige ça, mais je voudrais ton aide. Je ne vois comment ajouter un test qui illustre ce cas, vu que c'est assez aléatoire. 

Si tu as des idée , je suis preneur

**Comment by larochef** [comment]
Je pense que la meilleure solution serait de fixer l'IP des conteneurs pour
être sûrs qu'elle ne change pas.

L'autre soucis des changements d'ip est que des trucs comme java cachent
les DNS, d'autres s'initialisent avec les ips.

François

**Comment by ylorenza** [comment]
Pas idiot, c'est faisable a partir de la 1.10. Je regarderai ça lundi

**Comment by larochef** [comment]
Fixed with commit 589162073c56f5769c0eb844d5434c5f5c8d4bb5
