### ISSUE TITLE
Avoir un label maze (ou autre) au run des container afin de les nettoyer plus simplement

### ISSUE THREAD

**Issue by ylorenza** [voyages-sncf-technologies/maze#7]
ça serai pas mal d'avoir sur les container un label "maze" par défaut afin de pouvoir nettoyer simplement en cas de crash.

ex : dans ma ci au début de chaque run j'ai 
docker rm -fv $(docker ps -qa --filter="label=application.name=maze")
comme ça, je repart proprement a chaque build

on pourrait meme envisager avec ce label d’intégrer le nettoyage dans le beforeAll

**Comment by larochef** [comment]
Super idée d'ajouter un label. application.name posera certainement des soucis pour la "mazification" strowgr et le registrator, à nous de trouver une clé différente, genre test.runner=maze

**Comment by larochef** [comment]
Je commence à regarder ce que ça donnerait, sur la branche "review-configuration"

**Comment by larochef** [comment]
Corrigé par #13
